<?php

/**
 * BaseDay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date
 * @property string $title
 * @property float $start_latt
 * @property float $start_long
 * @property float $end_latt
 * @property float $end_long
 * @property clob $notes
 * 
 * @method date   getDate()       Returns the current record's "date" value
 * @method string getTitle()      Returns the current record's "title" value
 * @method float  getStartLatt()  Returns the current record's "start_latt" value
 * @method float  getStartLong()  Returns the current record's "start_long" value
 * @method float  getEndLatt()    Returns the current record's "end_latt" value
 * @method float  getEndLong()    Returns the current record's "end_long" value
 * @method clob   getNotes()      Returns the current record's "notes" value
 * @method Day    setDate()       Sets the current record's "date" value
 * @method Day    setTitle()      Sets the current record's "title" value
 * @method Day    setStartLatt()  Sets the current record's "start_latt" value
 * @method Day    setStartLong()  Sets the current record's "start_long" value
 * @method Day    setEndLatt()    Sets the current record's "end_latt" value
 * @method Day    setEndLong()    Sets the current record's "end_long" value
 * @method Day    setNotes()      Sets the current record's "notes" value
 * 
 * @package    followben
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDay extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('day');
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('start_latt', 'float', null, array(
             'type' => 'float',
             'length' => '',
             ));
        $this->hasColumn('start_long', 'float', null, array(
             'type' => 'float',
             'length' => '',
             ));
        $this->hasColumn('end_latt', 'float', null, array(
             'type' => 'float',
             'length' => '',
             ));
        $this->hasColumn('end_long', 'float', null, array(
             'type' => 'float',
             'length' => '',
             ));
        $this->hasColumn('notes', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}