<?php

/**
 * BaseDay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date
 * @property string $title
 * @property clob $notes
 * 
 * @method date   getDate()  Returns the current record's "date" value
 * @method string getTitle() Returns the current record's "title" value
 * @method clob   getNotes() Returns the current record's "notes" value
 * @method Day    setDate()  Sets the current record's "date" value
 * @method Day    setTitle() Sets the current record's "title" value
 * @method Day    setNotes() Sets the current record's "notes" value
 * 
 * @package    followben
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDay extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('day');
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('notes', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}