actAs:
  Timestampable: ~

Tweet:
  columns:
    id:
      type: bigint
      primary: true
    text:
      type: string(140)
      notnull: true
    html:
      type: string()
      notnull: true
    uri:
      type: string(255)
      notnull: true
    reply_id:
      type: bigint
    reply_user_id:
      type: integer(4)
    reply_username:
      type: string(100)
    language:
      type: string(2)
      notnull: true
    source:
      type: string(255)
      notnull: true
  options:
    orderBy: id DESC